#!/bin/bash

ENABLED=""
DISABLED=""
# Toggle DND
if [ "$(makoctl mode)" == "do-not-disturb" ]; then
  makoctl mode -r do-not-disturb
else
  # DND ON
  makoctl mode -s do-not-disturb >/dev/null
fi

sleep 0.1
